services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        image: grom_api
        container_name: grom_api
        volumes:
            - .:/app:z
            - ./staticfiles:/app/staticfiles
        ports:
            - "8000:8000"
        # expose:
        #     - "8000"
        env_file:
            - ./.envs/.env.local
        depends_on:
            - postgres
        command: /start
        networks:
            - grom_nw

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        image: grom_postgres
        container_name: grom_postgres
        ports:
            - "5432:5432"
        volumes:
            - grom_postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.envs/.env.local
        networks:
            - grom_nw

    node:
        build:
            context: .
            dockerfile: ./docker/local/node/Dockerfile
        image: grom_local_node
        container_name: grom_local_node
        tty: true
        depends_on:
            - api
        volumes:
            - .:/app:z
            - /app/node_modules
        command: npm run styles
        ports:
            - "3000:3000"

networks:
    grom_nw:
        external: true

volumes:
    grom_postgres_data: {}
