---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Make envfile
              working-directory: .envs
              run: |
                  touch .env.local
                  echo DEBUG=false >> .env.local
                  echo_SITE_NAME="Site" >> .env.local
                  echo DJANGO_SECRET_KEY="somesecretkey" >> .env.local
                  echo DJANGO_ADMIN_URL="admin" >> .env.local
                  echo POSTGRES_HOST="postgres" >> .env.local
                  echo POSTGRES_PORT="5432" >> .env.local
                  echo POSTGRES_DB="somedb" >> .env.local
                  echo POSTGRES_USER="dbuser" >> .env.local
                  echo POSTGRES_PASSWORD="somepass123" >> .env.local
                  cat .env.local
            - name: Create Docker Network
              run: docker network create grom_nw
            - name: Lint
              run: docker compose -f local.yml run --rm api flake8 .
            - name: Test
              run: docker-compose run --rm api pytest
